"""Test

Revision ID: 1038b4caee2
Revises: 
Create Date: 2015-06-20 14:09:39.369702

"""
import datetime

# revision identifiers, used by Alembic.
revision = '1038b4caee2'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=True),
    sa.Column('slug', sa.String(length=6), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('referral_program_slug_index', 'referral_program', ['slug'], unique=True)
    op.create_table('referral_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_program_id', sa.Integer(), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referral_program_id'], ['referral_program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_conversion')
    op.drop_index('referral_program_slug_index', table_name='referral_program')
    op.drop_table('referral_program')
    ### end Alembic commands ###
