"""Adding paid marker, referral program type.

Revision ID: 23f0ed45109
Revises: 5a8fdf030f9
Create Date: 2015-07-12 22:23:51.702135

"""
import datetime

# revision identifiers, used by Alembic.
revision = '23f0ed45109'
down_revision = '5a8fdf030f9'
branch_labels = None
depends_on = None

from alembic import op
from alembic import context
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        has_type = connection.execute(
                "select exists (select 1 from pg_type "
                "where typname='size_type')").scalar()
        if not has_type:
            connection.execute("CREATE TYPE referral_program_type AS ENUM ('internal', 'referral', 'affiliate')")

    op.add_column('referral_conversion', sa.Column('paid_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=True))
    op.add_column('referral_program', sa.Column('program_type', sa.Enum('internal', 'referral', 'affiliate', name='referral_program_type'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_program', 'program_type')
    op.drop_column('referral_conversion', 'paid_at')
    ### end Alembic commands ###
